---
title: "Food security and nutrition"
description: "Suite of Food Security Indicators"
author: 
    - name: "Ítalo Marques-Monteiro"
    - email: "italo.marques.monteiro@outlook.com"
    - github: https://github.com/italomarquesmonteiro
    - kaggle: https://www.kaggle.com/talomarquesmonteiro
    - linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    - lattes: http://lattes.cnpq.br/7174985368517137
    - orcid_id: https://orcid.org/0000-0003-4367-1034
    - affiliation: Smart Data  
        
date: "2023-11-18"
output: html_document
---


```{r}
library(tidyverse)
```

    Crops and livestock products
        Culturas e produtos pecuários
```{r}
nutrition <- readr::read_csv(
    "c:/Users/italo/OneDrive/Área de Trabalho/VsCode/faostats/FAOStats Average supply of protein of animal origin.csv") |> # nolint
    janitor::clean_names("snake") |>
    dplyr::mutate(
        name = dplyr::if_else(
            stringr::str_detect(
                area, "China"), "China", area),
        name = dplyr::case_when(
            area == "Bolivia (Plurinational State of)" ~ "Bolivia",
            area == "Czechia" ~ "Czech Republic",
            area == "Democratic People's Republic of Korea" ~ "Dem. Rep. Korea",
            area == "Iran (Islamic Republic of)" ~ "Iran",
            area == "Lao People's Democratic Republic" ~ "Lao PDR",
            area == "Syrian Arab Republic" ~ "Syria",
            area == "Türkiye" ~ "Turkey",
            area == "United Republic of Tanzania" ~ "Tanzania",
            area == "United States of America" ~ "United States",
            area == "Venezuela (Bolivarian Republic of)" ~ "Venezuela",
            area == "Viet Nam" ~ "Vietnam",
            TRUE~ area
        ), .before = element_code
    ) |>
    dplyr::select(name, element, item_code, item, unit, value) |>
    dplyr::glimpse()
```

```{r}
nutrition_new <- nutrition |>
    dplyr::filter(
        item == "Average supply of protein of animal origin (g/cap/day) (3-year average)"
    ) |>
    #dplyr::mutate(value = readr::parse_number(value)) |>
    dplyr::glimpse()
```


    World map data
        Dados do mapa do mundo
```{r}
world <- rnaturalearth::ne_countries(
  scale = 110, type = "countries", returnclass = "sf") |>
  dplyr::select(name_long) |>
  dplyr::glimpse()
```


```{r}
join <- world |>
    #dplyr::anti_join(production, by = c("name_long" = "area")) |>
    dplyr::full_join(nutrition_new, by = c("name_long" = "name")) 
```



```{r}
#viridris_option <- "inferno"
title_text <- glue::glue("Fornecimento médio de proteína de origem animal")
caption_text <- glue::glue("**Dados** FAOStats (média de 2018 a 2020) **| Gráfico** Ítalo Monteiro") # nolint

p1 <- ggplot(join) +
    geom_sf(aes(fill = value)) +
    scico::scale_fill_scico(palette = "bamako", direction = -1) +
    #scale_fill_viridis_c(
    #option = viridris_option
    #) +
  scale_y_continuous(labels = scales::comma) +
    labs(
        fill = "g/per capita/dia",
        title = title_text,
        caption = caption_text
    )
#p1
```


```{r}
col_back <- "grey10"
theme_map <- theme_void() +
    theme(
        plot.title = ggtext::element_markdown(face = "bold", family = "Source Sans Pro", size = 24, hjust = 0.5, color = "grey70",),  #nolint
        plot.caption = ggtext::element_markdown(face = "italic", family = "Fira Sans Pro", size = 12, color = "grey70"), # nolint
        legend.position = "bottom",
        legend.text = element_text(color = "grey70"),
        plot.margin = margin(1, 1, 1, 1, "cm"),
        plot.background = element_rect(fill = col_back, color = NA),
        legend.title = element_text(
            face = "bold",
            color = "grey70",
            margin = margin(0, 0, 0.25, 0, "cm")
        )
    )
p2 <- p1 + theme_map
#p2
```


```{r}
sf::st_crs(join)
```

```{r}
p3 <- p2 +
    coord_sf(crs = "+proj=robin")
#p3
```


```{r}
grat <- sf::st_graticule(lat = c(-89.9, seq(-80, 80, 20), 89.9))
 
p3b  <- p2 + 
    geom_sf(
        grat, mapping = aes(
            geometry = geometry),
            color = "gray70", 
        alpha = 0.5
  ) +
  coord_sf(crs = "+proj=robin") +
   guides(fill = guide_colorbar(
    direction = "horizontal",
    title.position = "top",
        title.hjust = .5,
        title.vjust = .1,
            barwidth = 20,
                 barheight = .5))
p3b
```


```{r}
ggsave("Food segurity/NecessidadeMediaEnergiaDierta.png", plot = p3b, dpi = 450)
```